spring:
 application:
  name: snatch-gateway
 cloud:
  gateway:
   routes:
   - id: heist-api-route
     uri: lb://heist-api
     predicates:
     - Path=/heist/**
   - id: inventory-api-route
     uri: lb://inventory-api
     predicates:
     - Path=/loot/**
   - id: personnel-management-api-route
     uri: lb://personnel-management-api
     predicates:
     - Path=/**

server:
 port: 9000
 
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka